spring:
    application:
        name: poll
    datasource:
        driverClassName: org.postgresql.Driver
        url: ${POSTGRES_URL_DATABASE}
        username: ${POSTGRES_USER}
        password: ${POSTGRES_PASSWORD}
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                # '[format_sql]': true
                '[default_schema]': poll
    flyway:
        default-schema: poll
    sql:
        init:
            mode: always
            schema-locations: classpath:schema.sql
    rabbitmq:
        publisher-confirm-type: correlated

poll:
    session:
        result:
            cron: 0 0/1 * * * *
            queue: poll-session-result-queue

api:
    validator:
        url: http://localhost:8081
        token: ${API_VALIDATOR_TOKEN}