spring:
    application:
        name: poll
    datasource:
        driverClassName: org.postgresql.Driver
        url: ${POSTGRES_URL_DATABASE}
        username: ${POSTGRES_USER}
        password: ${POSTGRES_PASSWORD}
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                '[format_sql]': true
                '[default_schema]': poll
    flyway:
        default-schema: poll
    sql:
        init:
            mode: always
            schema-locations: classpath:schema.sql
