spring:
    application:
        name: poll
    datasource:
        driverClassName: org.postgresql.Driver
        url: ${POSTGRES_URL_DATABASE}
        username: ${POSTGRES_USER}
        password: ${POSTGRES_PASSWORD}
    jpa:
        hibernate:
            ddl-auto: update

api:
    key: ${API_KEY}